language: go
sudo: required
services:
- docker
go:
- 1.7
env:
  global:
  - GOARCH=amd64
before_deploy: make ci
deploy:
  provider: releases
  api_key:
    secure: IFy47qRhLVBND/gQskxy0+r8DVxKFe0xUQNocjNQWqjQT37lelnkBGDITjdlxco0sOgwhB71fA3xf2PD2WhAPxD2NHBGfTYvc9SrnaBUVFAAItMaX1C31NMnxwhWIQfT9UHeRSOLoIGZEkvIoFAtnOZDcaQC+rqI0fJtJ9ax7EvZoxUTxUhjrTbwUv3mDP5cYtJST657OIyXWwEGI1LGS9w9J8GZSXv7Uh0AjCbT8pTWtzg/Ixb7BlzGqtkE6tk6QbR/U8L5zB01D3hwbtCrhwW0B3UFAIe8EvJ28ql1vYfOojb8e4QTPTUDqJM05+0br8zhJ+DmuOrFQh68fpzMI9akxRsiX3lX/gs3H8x0IGL0LnN5xoNRXzoPEp+kE6ATUK2mE/ayoC087IthxdACK/xjdo2/ebqNcaO2cDdHHYyEE1Dl7QJ0zbHp2DAK72IMQlGrAVRIep0aS4lWtLHkycBWw29GutpujrMnSREOC/7KRDd4cALKRC+Nw3tesmSytOHdeR0WatIFdv1pF81Nqy7XBKQC8+Vnievx3Yb1lIzFzn5G06OtGJNXQ2YMpDsU9jLbCWrSp/Jpwsz38Y7vf70DZGxpqAR3lozR+dMBVuX/3CzHi0zekDCDuu5DS0XspuXQwd7pN2s0ap6gUaev3q3sOf9VBbV1fnHzOBgYFCs=
  file_glob: true
  file:
    - "build/rpm/*.rpm"
    - "build/tgz/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true