version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    expose:
      - 9090
    links:
      - cloudmonitor:cloudmonitor
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana

  lb:
    image: dockercloud/haproxy
    links:
      - cloudmonitor
    environment:
      - CERT_FOLDER="/certs/"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert.pem:/certs/cert1.pem
    ports:
      - 80:80
      - 443:443

  cloudmonitor:
    build: ..
    expose:
      - 9143
    ports:
     - "9143:9143"

